### ISSUE TITLE
Index 2 images from Eiger detector

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#27]
Need to index 2 hdf5 images from Eiger detector

[260_1_1_6_S.002_data_000001.h5.zip](https://github.com/RAPD/RAPD/files/1056285/260_1_1_6_S.002_data_000001.h5.zip)
[260_1_1_6_S.001_data_000001.h5.zip](https://github.com/RAPD/RAPD/files/1056284/260_1_1_6_S.001_data_000001.h5.zip)

**Comment by frankvm04** [comment]
I should have this done this weekend.

**Comment by frankvm04** [comment]
Are these files master files? Or is there a way I am unfamiliar with to grab the data without master files?

**Comment by jbrunzelle** [comment]
they are master files

Joseph S Brunzelle, PhD
Assistant Research Professor
Dept. Mol Pharm & Bio Chem
Life Sciences Collaborative Access Team
Synchrotron Research Center, Northwestern University
Ph. 630-343-9825 Fax. 630-252-4664
j-brunzelle@northwestern.edu
http://www.ls-cat.org

**Comment by frankvm04** [comment]
Are you able to open them? If so, how?

I am having trouble opening them. (Obviously)

Fm

**Comment by jbrunzelle** [comment]
Let me check
