### ISSUE TITLE
Index failure with lscat_rayonix_mx300

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#40]
Try to in index 2 files from lscat_rayonix_mx300 and get the following error

rapd.index ../CF267-BE1_2_2_3_S.001 ../CF267-BE1_2_2_3_S.002

---------------------
RAPD Index & Strategy
---------------------
analyze_data_sources ['../CF267-BE1_2_2_3_S.001', '../CF267-BE1_2_2_3_S.002']
  source_abspath: /pf/esafs/edu/wayne/med/zyang/167213/f/Yang_20170708_21F/screen/CF267-BE1/CF267-BE1_2_2_3_S.001
  source_abspath: /pf/esafs/edu/wayne/med/zyang/167213/f/Yang_20170708_21F/screen/CF267-BE1/CF267-BE1_2_2_3_S.002

Data file(s)
  /pf/esafs/edu/wayne/med/zyang/167213/f/Yang_20170708_21F/screen/CF267-BE1/CF267-BE1_2_2_3_S.001
  /pf/esafs/edu/wayne/med/zyang/167213/f/Yang_20170708_21F/screen/CF267-BE1/CF267-BE1_2_2_3_S.002
CF267-BE1_2_2_3_S.001
['CF267-BE1_2_2_3_S', '001']
['CF267-BE1', '2', '2', '3', 'S']
S
Traceback (most recent call last):
  File "/pf/local/rapd/src/plugins/index/commandline.py", line 535, in <module>
    main()
  File "/pf/local/rapd/src/plugins/index/commandline.py", line 475, in main
    image_headers[data_file] = detector_module.read_header(data_file)
  File "/pf/local/rapd/src/sites/detectors/lscat_rayonix_mx300.py", line 303, in read_header
    header["run_number"] = int(basename.split(".")[-2].split("_")[-1])
ValueError: invalid literal for int() with base 10: 'S'

**Comment by schuerjp1** [comment]
Fixed.

**Comment by jbrunzelle** [comment]
Thank you, just tested and works fine

Joseph S Brunzelle, PhD
Assistant Research Professor
Dept. Mol Pharm & Bio Chem
Life Sciences Collaborative Access Team
Synchrotron Research Center, Northwestern University
Ph. 630-343-9825 Fax. 630-252-4664
j-brunzelle@northwestern.edu
http://www.ls-cat.org
