### ISSUE TITLE
Can't index images due to filename parsing

### ISSUE THREAD

**Issue by frankvm04** [RAPD/RAPD#44]
Files from LS-CAT

CF267-BE1_2_2_3_S.002
CF267-BE1_2_2_3_S.001

**Comment by frankvm04** [comment]
This is due to a missing line in the BEST_INFO that describes a problem in the best detector info dat file (missing description)

**Comment by schuerjp1** [comment]
I believe this was due to the MAR detector description not being in the BEST detector_info.dat file. The Eiger HDF5toCBF conversion naming issue should be resolved now.
