### ISSUE TITLE
rapd.integrate naming issues

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#47]
get the following error if I integrate this data first, IDP07311-5.002_master.h5

rapd.integrate ../IDP07311-5.002_master.h5

---------------
RAPD Intgration
---------------
analyze_data_sources ../IDP07311-5.002_master.h5
Employing multiple threads

HDF5 source file(s)
  /pf/esafs/edu/northwestern/k-brister/161045/d/JSB/20170419/RT-IDP07311/IDP07311-5.002_master.h5

Data files

XDS processing
  Searching for peaks. done
  Indexing. done
  Integrating. done
  Checking XDS output for errors

XDS error unknown to RAPD has occurred. Please check for cause!
Process FastIntegration:
Traceback (most recent call last):
  File "/pf/local/rapd/share/cctbx/base/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/pf/local/rapd/src/plugins/integrate/plugin.py", line 298, in run
    self.process()
  File "/pf/local/rapd/src/plugins/integrate/plugin.py", line 356, in process
    integration_results = self.xds_total(xds_input)
  File "/pf/local/rapd/src/plugins/integrate/plugin.py", line 640, in xds_total
    raise Exception("XDS error unknown to RAPD has occurred.")
Exception: XDS error unknown to RAPD has occurred.

If I integrate IDP07311-5.001_master.h5 first (that runs fine) then run IDP07311-5.002_master.h5, it will work fine.  So, there is a problem with run number confusion.

I will send an email with the data files

**Comment by schuerjp1** [comment]
fixed
