### ISSUE TITLE
Specifying cell and space group parameters for indexing doesn't work

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#49]
Have a case where the system indexes as a tetragonal group but is actually C centred orthogonal.  Tried to specify on the command line  
rapd.index -sg C2221 -u 207 207.2 88.8 90 90 90 ../NLG1168_2_2_8_S.001_master.h5

the results follow as:

Highest symmetry Labelit result  
  Solution  Metric fit  rmsd  #spots  crystal_system   unit_cell                                  volume
  :)   9     0.4392 dg 0.145    106    tetragonal tP  146.46 146.46  88.80  90.00  90.00  90.00  1904886
  :)   8     0.4392 dg 0.089    104  orthorhombic oC  207.03 207.19  88.79  90.00  90.00  90.00  3808532
  :)   7     0.4392 dg 0.124    104    monoclinic mC  207.26 207.42  88.83  90.00  90.21  90.00  3818701
  :)   6     0.4188 dg 0.136    104    monoclinic mC  207.18 207.02  88.84  90.00  89.75  90.00  3810248
  :)   5     0.3219 dg 0.196    106  orthorhombic oP   88.66 146.51 147.07  90.00  90.00  90.00  1910465
  :)   4     0.3199 dg 0.252    107    monoclinic mP  146.51  88.76 147.26  90.00  89.95  90.00  1914942
  :)   3     0.3219 dg 0.204    106    monoclinic mP   88.63 146.98 146.58  90.00  89.97  90.00  1909361
  :)   2     0.0527 dg 0.188    105    monoclinic mP   88.83 146.37 147.23  90.00  89.68  90.00  1914332
  :)   1     0.0000 dg 0.185    106     triclinic aP   88.85 146.43 147.37  89.95  89.68  89.97  1917393
  
  MOSFLM Integration results:
  Solution  SpaceGroup Beam x   y  distance  Resolution Mosaicity RMS
  :)   9           P4  92.56 116.67  300.24       3.39    0.650000    0.067
       1           P1  92.56 116.49  299.82       3.39    0.650000    0.063

Sent image files to Jon

**Comment by schuerjp1** [comment]
fixed
