### ISSUE TITLE
Runaway Best job(s)

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#50]
During an index job, will get the following warning:

Starting strategy calculations
  Strategy calculation timed out
  Starting BEST runs
  Strategy calculation timed out
BEST unable to calculate a strategy
  Strategy calculation timed out
  Starting Mosflm runs
 the job completes but there are still at least a half dozen best jobs still running.  We are using Best Version 3.2.0  //  03.11.2008

**Comment by schuerjp1** [comment]
I think Joe fixed it with getting the correct beam center...
