### ISSUE TITLE
Indexing error

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#51]
Tried to index 2 frames from 21G (mar300) as following

rapd.index ../sla70TC_1_2_7.001 ../sla70TC_1_2_7.180

---------------------
RAPD Index & Strategy
---------------------
analyze_data_sources ['../sla70TC_1_2_7.001', '../sla70TC_1_2_7.180']
  source_abspath: /pf/esafs/edu/utmb/mawhite/171286/g/beam/KYChoi/1_2_7/sla70TC_1_2_7.001
  source_abspath: /pf/esafs/edu/utmb/mawhite/171286/g/beam/KYChoi/1_2_7/sla70TC_1_2_7.180

Data file(s)
  /pf/esafs/edu/utmb/mawhite/171286/g/beam/KYChoi/1_2_7/sla70TC_1_2_7.001
  /pf/esafs/edu/utmb/mawhite/171286/g/beam/KYChoi/1_2_7/sla70TC_1_2_7.180

Executable for raddose is not present - will continue

Starting indexing procedures
  Starting Labelit runs
    Looking for long unit cell
    Looking for stronger peaks (ie. small molecule)
    Looking for weak diffraction
    Setting spot picking level to 8
    Setting spot picking level to 6 and hires limit to 5Process RunLabelit:
Traceback (most recent call last):
  File "/pf/local/rapd/share/cctbx/base/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/pf/local/rapd/src/plugins/index/plugin.py", line 2123, in run
    self.labelit_run_queue()
  File "/pf/local/rapd/src/plugins/index/plugin.py", line 2681, in labelit_run_queue
    self.new_postprocess_labelit(raw_result=result)
  File "/pf/local/rapd/src/plugins/index/plugin.py", line 2535, in new_postprocess_labelit
    self.labelit_log[iteration].extend("\n%s\n" % problem_action['error'])
UnboundLocalError: local variable 'problem_action' referenced before assignment

Will send frames

**Comment by schuerjp1** [comment]
fixed
